name: Debug
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - run: |
        echo ${{ github.event.workflow_run }}
        echo ${{ github.event.workflow }}
        echo ${{ github.event.workflow.id }}
        echo ${{ github.event.workflow_run.run_number }}
