name: Debug
on:
  # workflow_run:
  #   workflows: ["BuildNumber"]
  #   types:
  #     - completed
  
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - run: |
        echo ${{ github.event.workflow_run }}
        echo ${{ github.event.workflow_run.run_number }}
